# Comments

services:
  backend:
    build: backend
    depends_on:
      - db
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 35729:35729
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

